- hosts: all
  remote_user: vagrant

  tasks:

  - name: Instalar GitHub,
    sudo: true
    apt:
      name: git
      state: latest

  - name: Install Python 3
    sudo: true
    apt:
      name: python3
      state: latest
      update_cache: yes

  - name: Instalar pip
    sudo: true
    apt:
      name: python3-pip
      state: latest
      update_cache: yes

  - name: clonar repositorio libsepe
    sudo: false
    git :
      repo: https://github.com/GinesNC/LibSePeBOT-IV.git
      dest: /home/vagrant/LibSePeBOT-IV
      force: yes

  - name: install requirements
    sudo: yes
    command: pip3 install -r /home/vagrant/LibSePeBOT-IV/requirements.txt
